Repository NeckSlicers/bookJagook, pull requests merged in 2022-12, with the labels that each got.

#2 Feature/style guide
  client/package-lock.json
  client/package.json
  client/src/assets/logo.png
  client/src/components/atoms/Button.ts
  client/src/components/atoms/Input.ts
  client/src/components/atoms/Text.ts
  client/src/components/atoms/index.ts
  client/src/components/index.ts
  client/src/components/molecules/Header/index.tsx
  client/src/components/molecules/Header/styles.Header.ts
  client/src/components/molecules/Modal/index.tsx
  client/src/components/molecules/Modal/styles.Modal.ts
  client/src/components/molecules/index.ts
  client/src/constants/index.ts
  client/src/constants/theme.ts
  client/src/pages/Home/index.tsx
Labels: ✨ UI/UX, 📱 FE

#13 Feature/#8/mybooks styling -> dev/client로 merge
  client/src/components/atoms/Input.ts
  client/src/components/index.ts
  client/src/components/molecules/Header/index.tsx
  client/src/components/molecules/Header/styles.Header.ts
  client/src/components/molecules/Modal/index.tsx
  client/src/components/molecules/Modal/styles.Modal.ts
  client/src/constants/theme.ts
  client/src/pages/Home/index.tsx
  client/src/pages/MyBooks/Books/index.tsx
  client/src/pages/MyBooks/Books/styles.Books.ts
  client/src/pages/MyBooks/index.tsx
  client/src/types/index.ts
  client/src/types/modals.ts
Labels: ✨ UI/UX, 📱 FE

#15 Feature/#9/home-styling -> dev/client로 merge
  client/src/pages/Home/index.tsx
Labels: ✨ UI/UX, 📱 FE, ⭐ 중요도

#12 Feature/mongodb
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/api/axios.ts
  server/src/api/index.ts
  server/src/api/path.ts
  server/src/api/request.ts
  server/src/controllers/bookController.ts
  server/src/controllers/bookListController.ts
  server/src/controllers/index.ts
  server/src/controllers/userController.ts
  server/src/controllers/wishListController.ts
  server/src/env.d.ts
  server/src/index.ts
  server/src/models/index.ts
  server/src/models/mybook.ts
  server/src/models/review.ts
  server/src/models/user.ts
  server/src/models/wishList.ts
  server/src/routes/book.ts
  server/src/routes/bookList.ts
  server/src/routes/index.ts
  server/src/routes/mybook.ts
  server/src/routes/mybookList.ts
  server/src/routes/user.ts
  server/src/routes/wishiList.ts
  server/src/types/index.ts
  server/tsconfig.json
Labels: 🖥 BE, 💾 데이터 베이스

#17 Feature/#8/mybooks styling
  client/public/index.html
  client/src/components/atoms/Button.ts
  client/src/components/atoms/Input.ts
  client/src/components/index.ts
  client/src/components/molecules/Modal/ModalContainer.tsx
  client/src/components/molecules/Modal/index.tsx
  client/src/components/molecules/MyBooks/Books/Book/BookInfo.tsx
  client/src/components/molecules/MyBooks/Books/Book/index.tsx
  client/src/components/molecules/MyBooks/Books/Book/styles.BookInfo.ts
  client/src/components/molecules/MyBooks/Books/Book/styles.ts
  client/src/components/molecules/MyBooks/Books/index.tsx
  client/src/components/molecules/MyBooks/Books/styles.ts
  client/src/pages/Home/index.tsx
  client/src/pages/Home/styles.Home.ts
  client/src/pages/MyBooks/Books/index.tsx
  client/src/pages/MyBooks/index.tsx
  client/src/types/modals.ts
Labels: ✨ UI/UX, 📱 FE, ⭐ 중요도
